Repository buddy-ya/be, pull requests merged in 2024-11, with the labels that each got.

#5 feat: MySQL 기본 설정 Student 기본 Entity 생성
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/resources/application.properties
Labels: ⚙ Setting, ✨ Feature

#7 feat: SOLAPI API를 사용한 인증코드 전송 & 인증 코드 검증 기능 구현
  build.gradle
  src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhoneNumber.java
  src/main/java/com/team/buddyya/certification/dto/request/SendCodeRequest.java
  src/main/java/com/team/buddyya/certification/dto/request/VerifyCodeRequest.java
  src/main/java/com/team/buddyya/certification/dto/response/SendCodeResponse.java
  src/main/java/com/team/buddyya/certification/dto/response/VerifyCodeResponse.java
  src/main/java/com/team/buddyya/certification/exception/PhoneAuthenticationErrorCode.java
  src/main/java/com/team/buddyya/certification/exception/PhoneAuthenticationException.java
  src/main/java/com/team/buddyya/certification/repository/RegisteredPhoneRepository.java
  src/main/java/com/team/buddyya/certification/service/MessageSendService.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/common/exception/ErrorResponse.java
  src/main/java/com/team/buddyya/common/exception/GlobalExceptionHandler.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/repository/AvatarRepository.java
  src/main/resources/application.properties
Labels: ⚙ Setting, ✨ Feature, 📬 API

#11 fix: test 배포 서버 DB 설정 정보 수정
  src/main/resources/application-dev.properties
Labels: 🌏 Deploy

#9 feat: 인증 및 인가 처리를 위한 Security 설정
  build.gradle
  src/main/java/com/team/buddyya/auth/domain/AuthToken.java
  src/main/java/com/team/buddyya/auth/domain/CustomUserDetails.java
  src/main/java/com/team/buddyya/auth/domain/StudentInfo.java
  src/main/java/com/team/buddyya/auth/dto/request/TokenInfoRequest.java
  src/main/java/com/team/buddyya/auth/exception/AuthException.java
  src/main/java/com/team/buddyya/auth/exception/AuthExceptionType.java
  src/main/java/com/team/buddyya/auth/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/team/buddyya/auth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
  src/main/java/com/team/buddyya/auth/jwt/JwtExceptionFilter.java
  src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
  src/main/java/com/team/buddyya/auth/repository/AuthTokenRepository.java
  src/main/java/com/team/buddyya/auth/service/CustomUserDetailsService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/dto/response/OnBoardingResponse.java
  src/main/java/com/team/buddyya/student/exception/OnBoardingExceptionType.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/resources/application.properties
Labels: ✨ Feature, 🥰 Accessibility

#14 feat: 토큰 만료 시 재발급 기능
  src/main/java/com/team/buddyya/auth/controller/AuthController.java
  src/main/java/com/team/buddyya/auth/dto/request/TokenReissueRequest.java
  src/main/java/com/team/buddyya/auth/dto/response/TokenReissueResponse.java
  src/main/java/com/team/buddyya/auth/exception/AuthExceptionType.java
  src/main/java/com/team/buddyya/auth/service/AuthService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
Labels: ✨ Feature, 📬 API, 🥰 Accessibility

#17 feat: 한국인 학생 이메일 인증 api
  build.gradle
  src/main/java/com/team/buddyya/certification/controller/CertificationController.java
  src/main/java/com/team/buddyya/certification/dto/request/EmailCertificationRequest.java
  src/main/java/com/team/buddyya/certification/dto/request/EmailCodeRequest.java
  src/main/java/com/team/buddyya/certification/dto/response/EmailCertificationResponse.java
  src/main/java/com/team/buddyya/certification/exception/EmailCertificateException.java
  src/main/java/com/team/buddyya/certification/exception/EmailCertificateExceptionType.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/resources/application.properties
  src/test/java/com/team/buddyya/certification/service/CertificationServiceTest.java
Labels: ✨ Feature, 📬 API

#19 feat: 외국인 학생 학생증 인증 api
  build.gradle
  src/main/java/com/team/buddyya/BuddyyaApplication.java
  src/main/java/com/team/buddyya/auth/domain/AuthToken.java
  src/main/java/com/team/buddyya/auth/exception/AuthException.java
  src/main/java/com/team/buddyya/auth/service/CustomUserDetailsService.java
  src/main/java/com/team/buddyya/certification/controller/CertificationController.java
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
  src/main/java/com/team/buddyya/certification/dto/response/CertificationResponse.java
  src/main/java/com/team/buddyya/certification/dto/response/EmailCertificationResponse.java
  src/main/java/com/team/buddyya/certification/exception/CertificateException.java
  src/main/java/com/team/buddyya/certification/exception/CertificateExceptionType.java
  src/main/java/com/team/buddyya/certification/exception/EmailCertificateException.java
  src/main/java/com/team/buddyya/certification/exception/PhoneAuthenticationException.java
  src/main/java/com/team/buddyya/certification/repository/StudentIdCardRepository.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/common/config/S3Config.java
  src/main/java/com/team/buddyya/common/domain/BaseTime.java
  src/main/java/com/team/buddyya/common/domain/CreatedTime.java
  src/main/java/com/team/buddyya/common/domain/S3DirectoryName.java
  src/main/java/com/team/buddyya/common/exception/CommonException.java
  src/main/java/com/team/buddyya/common/exception/CommonExceptionType.java
  src/main/java/com/team/buddyya/common/exception/ExceptionResponse.java
  src/main/java/com/team/buddyya/common/exception/GlobalExceptionHandler.java
  src/main/java/com/team/buddyya/common/service/S3UploadService.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/domain/Gender.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/domain/StudentInterest.java
  src/main/java/com/team/buddyya/student/domain/StudentLanguage.java
  src/main/java/com/team/buddyya/student/exception/StudentException.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/service/StudentInterestService.java
  src/main/java/com/team/buddyya/student/service/StudentLanguageService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/application.properties
Labels: ✨ Feature, 📬 API

#25 feat: 관리자의 학생증 인증 승인, 반려하는 기능
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
  src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardListResponse.java
  src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardResponse.java
  src/main/java/com/team/buddyya/admin/dto/response/StudentVerificationResponse.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
  src/main/java/com/team/buddyya/certification/repository/StudentIdCardRepository.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/common/service/S3UploadService.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/repository/StudentRepository.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: ✨ Feature, 📬 API

#27 feat: 재학생 인증 부분 기능 추가
  src/main/java/com/team/buddyya/certification/controller/CertificationController.java
  src/main/java/com/team/buddyya/certification/dto/response/CertificationResponse.java
  src/main/java/com/team/buddyya/certification/dto/response/CertificationStatusResponse.java
  src/main/java/com/team/buddyya/certification/dto/response/StudentIdCardResponse.java
  src/main/java/com/team/buddyya/certification/exception/CertificateExceptionType.java
  src/main/java/com/team/buddyya/certification/repository/StudentIdCardRepository.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/repository/StudentRepository.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: ✨ Feature, 📬 API

#31 feat: 피드 검색 기능 구현
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: ✨ Feature

#33 fix: Feed 부분 Formdata 문제 해결
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/resources/application.properties
Labels: 🐞 BugFix

#37 fix: Feed 부분 Formdata 문제 해결
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedUpdateRequest.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-local.properties
Labels: 🐞 BugFix

#40 feat: 좋아요 10개 이상 피드 조회
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: ✨ Feature, 📬 API

#38 feat: 학생 기본 프로필 추가
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentCreateResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentUpdateResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/student/controller/MyPageController.java
  src/main/java/com/team/buddyya/student/domain/ProfileDefaultImage.java
  src/main/java/com/team/buddyya/student/domain/ProfileImage.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/dto/response/MyPageResponse.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
  src/main/java/com/team/buddyya/student/service/MyPageService.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/java/com/team/buddyya/student/service/ProfileImageService.java
Labels: ✨ Feature, 📬 API

#42 fix : feed 수정 시 기존 이미지 중복 업데이트 오류 수정 & 프로필 수정 POST->PATCH
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/domain/Feed.java
  src/main/java/com/team/buddyya/feed/respository/FeedImageRepository.java
  src/main/java/com/team/buddyya/feed/service/FeedImageService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/student/controller/MyPageController.java
  src/main/java/com/team/buddyya/student/domain/ProfileImage.java
  src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
  src/main/java/com/team/buddyya/student/service/ProfileImageService.java
Labels: 🐞 BugFix
