Repository buddy-ya/be, pull requests merged in 2025-05, with the labels that each got.

#316 refactor: 출석 이벤트 참여 포인트 지급 기능 별도의 API로 분리
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/point/controller/PointController.java
  src/main/java/com/team/buddyya/point/domain/PointChangeType.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/point/dto/PointMissionResponse.java
  src/main/java/com/team/buddyya/point/dto/PointMissionRewardResponse.java
  src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
  src/main/java/com/team/buddyya/point/service/PointService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#329 refactor: 상대방 프로필 조회시 인증 여부 추가
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
Labels: 🔨 Refactor

#331 기존 회원가입 포인트 정책 개선 및 인증 미션 도입
  src/main/java/com/team/buddyya/admin/dto/response/StudentVerificationResponse.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/certification/controller/CertificationController.java
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/dto/response/CertificationResponse.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/mission/controller/MissionController.java
  src/main/java/com/team/buddyya/mission/dto/PointMissionResponse.java
  src/main/java/com/team/buddyya/mission/dto/PointMissionRewardResponse.java
  src/main/java/com/team/buddyya/mission/service/MissionService.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/point/controller/PointController.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/point/service/PointService.java
  src/main/resources/db/migration/V27__Add_registered_phone_number_has_certificated.sql
Labels: ✨ Feature

#336 refactor: 회원가입 포인트 정책 변경에 따른 NEW_SIGNUP 분리
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/point/service/PointService.java
Labels: 🔨 Refactor

#341 feat: 페스티벌 기간동안 회원 가입 시에 추가적인 리워드 지급
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/point/service/PointService.java
Labels: ✨ Feature

#348 feat: 피드 인기, 고정게시글 기능 구현
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/domain/Feed.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/exception/FeedExceptionType.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/student/domain/Role.java
  src/main/java/com/team/buddyya/student/domain/University.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/resources/db/migration/V28__Add_feed_pinned.sql
  src/main/resources/db/migration/V29__Add_university_match_and_feed_active.sql
  src/test/java/com/team/buddyya/student/controller/UserControllerTest.java
Labels: ✨ Feature

#353 refactor: 서울 선택 시 전체 대학 포함 & 하루 2회 매칭 가능하도록 변경
  src/main/java/com/team/buddyya/match/exception/MatchExceptionType.java
  src/main/java/com/team/buddyya/match/repository/MatchedHistoryRepository.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
Labels: 🔨 Refactor

#359 fix: 'pinned' 서비스에서 정렬 막힌 현상 해결 (#347)
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: 🐞 BugFix

#356 feat: 쿠폰 등록 이벤트 기능 구현
  src/main/java/com/team/buddyya/event/controller/EventController.java
  src/main/java/com/team/buddyya/event/domain/Coupon.java
  src/main/java/com/team/buddyya/event/dto/CouponRequest.java
  src/main/java/com/team/buddyya/event/dto/CouponResponse.java
  src/main/java/com/team/buddyya/event/exception/EventException.java
  src/main/java/com/team/buddyya/event/exception/EventExceptionType.java
  src/main/java/com/team/buddyya/event/repository/CouponRepository.java
  src/main/java/com/team/buddyya/event/service/EventService.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/resources/db/migration/V31__Create_coupon_table.sql
Labels: ✨ Feature

#361 feat: 유저 전체에게 알림이 가는 기능 구현
  src/main/java/com/team/buddyya/notification/controller/NotificationController.java
  src/main/java/com/team/buddyya/notification/dto/request/PushToAllUsersRequest.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
Labels: ✨ Feature

#363 fix: 로그인시 기존 유저일 경우 매칭 프로필 전달
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
Labels: 🐞 BugFix
