Repository buddy-ya/be, pull requests merged in 2025-02, with the labels that each got.

#84 feat: 피드와 채팅에서 신고하기, 마이페이지 나의 이미지 추가
  src/main/java/com/team/buddyya/chatting/domain/Report.java
  src/main/java/com/team/buddyya/chatting/dto/response/CreateChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/common/domain/S3DirectoryName.java
  src/main/java/com/team/buddyya/report/controller/ReportController.java
  src/main/java/com/team/buddyya/report/domain/Report.java
  src/main/java/com/team/buddyya/report/domain/ReportType.java
  src/main/java/com/team/buddyya/report/dto/ReportRequest.java
  src/main/java/com/team/buddyya/report/repository/ReportRepository.java
  src/main/java/com/team/buddyya/report/service/ReportService.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/domain/UserProfileDefaultImage.java
  src/main/java/com/team/buddyya/student/dto/request/UpdateProfileImageRequest.java
  src/main/java/com/team/buddyya/student/service/MyPageService.java
  src/main/java/com/team/buddyya/student/service/ProfileImageService.java
Labels: ✨ Feature, 📬 API

#86 refactor: 온보딩/휴대폰 인증 응답/유저정보수정 응답 DTO에 유저 정보 추가
  src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
  src/main/java/com/team/buddyya/certification/dto/response/VerifyCodeResponse.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java
  src/main/java/com/team/buddyya/student/domain/ProfileDefaultImage.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/domain/UserProfileDefaultImage.java
  src/main/java/com/team/buddyya/student/dto/response/MyPageUpdateResponse.java
  src/main/java/com/team/buddyya/student/dto/response/OnBoardingResponse.java
  src/main/java/com/team/buddyya/student/dto/response/UserProfileResponse.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/service/AvatarService.java
  src/main/java/com/team/buddyya/student/service/MyPageService.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/java/com/team/buddyya/student/service/ProfileImageService.java
  src/main/java/com/team/buddyya/student/service/StudentInterestService.java
  src/main/java/com/team/buddyya/student/service/StudentLanguageService.java
  src/main/java/com/team/buddyya/student/service/StudentMajorService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#87 feat: Expo Expo Push Notification을 활용한 알림 기능 구현
  build.gradle
  src/main/java/com/team/buddyya/common/config/RestTemplateConfig.java
  src/main/java/com/team/buddyya/notification/controller/NotificationController.java
  src/main/java/com/team/buddyya/notification/domain/ExpoToken.java
  src/main/java/com/team/buddyya/notification/domain/FcmToken.java
  src/main/java/com/team/buddyya/notification/domain/Notification.java
  src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
  src/main/java/com/team/buddyya/notification/dto/request/FeedNotificationRequest.java
  src/main/java/com/team/buddyya/notification/dto/request/NotificationRequest.java
  src/main/java/com/team/buddyya/notification/dto/request/SaveTokenRequest.java
  src/main/java/com/team/buddyya/notification/dto/response/NotificationResponse.java
  src/main/java/com/team/buddyya/notification/dto/response/SaveTokenResponse.java
  src/main/java/com/team/buddyya/notification/exception/NotificationException.java
  src/main/java/com/team/buddyya/notification/exception/NotificationExceptionType.java
  src/main/java/com/team/buddyya/notification/repository/ExpoTokenRepository.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/resources/application.properties
Labels: ✨ Feature, 📬 API

#62 feat: 피드 댓글 좋아요, 대댓글 기능 구현
  src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
  src/main/java/com/team/buddyya/chatting/domain/ChatRequest.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatRequestInfoResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatRequestResponse.java
  src/main/java/com/team/buddyya/chatting/exception/ChatExceptionType.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRequestRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
  src/main/java/com/team/buddyya/common/domain/BaseTime.java
  src/main/java/com/team/buddyya/feed/controller/BookmarkController.java
  src/main/java/com/team/buddyya/feed/controller/CommentController.java
  src/main/java/com/team/buddyya/feed/controller/FeedController.java
  src/main/java/com/team/buddyya/feed/controller/LikeController.java
  src/main/java/com/team/buddyya/feed/domain/Comment.java
  src/main/java/com/team/buddyya/feed/domain/CommentInfo.java
  src/main/java/com/team/buddyya/feed/domain/CommentLike.java
  src/main/java/com/team/buddyya/feed/domain/Feed.java
  src/main/java/com/team/buddyya/feed/domain/FeedLike.java
  src/main/java/com/team/buddyya/feed/dto/request/comment/CommentCreateRequest.java
  src/main/java/com/team/buddyya/feed/dto/response/LikeResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentCreateResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentUpdateResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedCreateResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/exception/FeedExceptionType.java
  src/main/java/com/team/buddyya/feed/respository/CommentLikeRepository.java
  src/main/java/com/team/buddyya/feed/respository/FeedLikeRepository.java
  src/main/java/com/team/buddyya/feed/service/CommentLikeService.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/student/domain/UserProfileDefaultImage.java
  src/main/resources/application-local.properties
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#88 feat: 채팅 요청 생성/삭제/조회 구현
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
Labels: ✨ Feature, 📬 API

#93 feat: 채팅방 조회, 채팅 관련 endpoint 수정
  src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomDetailResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/resources/application-local.properties
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#99 학생 인증 알림의 data에 인증 성공 여부 추가
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
Labels: 🔨 Refactor

#100 feat: 피드 대댓글 좋아요 상태 반환 및 오류 해결
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/repository/BookmarkRepository.java
  src/main/java/com/team/buddyya/feed/repository/CategoryRepository.java
  src/main/java/com/team/buddyya/feed/repository/CommentLikeRepository.java
  src/main/java/com/team/buddyya/feed/repository/CommentRepository.java
  src/main/java/com/team/buddyya/feed/repository/FeedImageRepository.java
  src/main/java/com/team/buddyya/feed/repository/FeedLikeRepository.java
  src/main/java/com/team/buddyya/feed/repository/FeedRepository.java
  src/main/java/com/team/buddyya/feed/service/BookmarkService.java
  src/main/java/com/team/buddyya/feed/service/CategoryService.java
  src/main/java/com/team/buddyya/feed/service/CommentLikeService.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedImageService.java
  src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: 🐞 BugFix, ✨ Feature, 📬 API

#105 알림 전송 기능에서 json 직렬화 문제 RequestNotification에 @Getter 추가해서 해결
  src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
Labels: 🐞 BugFix

#103 feat: https test를 위한 dummy api(#102)
  src/main/java/com/team/buddyya/auth/controller/AuthController.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
Labels: 🌏 Deploy, 📬 API

#108 chore: jwt 토큰 클레임 수정
  src/main/java/com/team/buddyya/auth/service/AuthService.java
Labels: 📬 API

#111 Deploy/https test
  src/main/resources/application.properties
Labels: 🥰 Accessibility

#112 refactor: 정책에 따라 refresh 토큰 재발급 받지 않도록 수정
  src/main/java/com/team/buddyya/auth/service/AuthService.java
Labels: 🥰 Accessibility

#97 feat: 회원 차단 기능 구현
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Block.java
  src/main/java/com/team/buddyya/student/dto/response/BlockResponse.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/repository/BlockRepository.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: ✨ Feature, 📬 API

#115 refactor: create_date -> created_date로 수정
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/common/domain/BaseTime.java
  src/main/java/com/team/buddyya/common/domain/CreatedTime.java
Labels: 🔨 Refactor

#120 refactor: 도메인 제약 조건 수정
  src/main/java/com/team/buddyya/admin/domain/Admin.java
  src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/auth/domain/AuthToken.java
  src/main/java/com/team/buddyya/certification/domain/StudentEmail.java
  src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/ChatRequest.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/java/com/team/buddyya/common/domain/BaseTime.java
  src/main/java/com/team/buddyya/common/domain/CreatedTime.java
  src/main/java/com/team/buddyya/notification/domain/ExpoToken.java
  src/main/java/com/team/buddyya/report/domain/Report.java
  src/main/java/com/team/buddyya/report/service/ReportService.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/domain/Buddy.java
  src/main/java/com/team/buddyya/student/domain/Interest.java
  src/main/java/com/team/buddyya/student/domain/Language.java
  src/main/java/com/team/buddyya/student/domain/Major.java
  src/main/java/com/team/buddyya/student/domain/Role.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/domain/University.java
  src/main/java/com/team/buddyya/student/repository/StudentRepository.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V1__init.sql
Labels: 🔨 Refactor

#125 마이그레이션 스크립트 수정
  src/main/java/com/team/buddyya/common/DataLoader.java
  src/main/resources/db/migration/V1__init.sql
Labels: 🔨 Refactor

#132 feat: 읽지 않은 총 메시지 개수 표시
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomListResponse.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/resources/db/migration/V2__Add_student_column_is_deleted.sql
Labels: ✨ Feature, 📬 API

#134 refactor: 사용자 정보 동기화를 위한 DTO에 프로필사진 등록 여부 추가
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 📬 API, 🔨 Refactor

#138 feat: 신고 시 저장 내용 수정 & 관리자 신고 조회
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/dto/response/AdminReportResponse.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/notification/dto/response/SaveTokenResponse.java
  src/main/java/com/team/buddyya/report/domain/Report.java
  src/main/java/com/team/buddyya/report/domain/ReportImage.java
  src/main/java/com/team/buddyya/report/dto/ReportRequest.java
  src/main/java/com/team/buddyya/report/repository/ReportImageRepository.java
  src/main/java/com/team/buddyya/report/service/ReportService.java
  src/main/resources/db/migration/V3__Update_Report_Table.sql
Labels: ✨ Feature, 📬 API
