Repository buddy-ya/be, pull requests merged in 2025-01, with the labels that each got.

#49 refactor: 온보딩과 휴대폰 인증 기능에서 논의한점 반영
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/domain/ProfileImage.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/domain/StudentInterest.java
  src/main/java/com/team/buddyya/student/domain/StudentLanguage.java
  src/main/java/com/team/buddyya/student/domain/StudentMajor.java
  src/main/java/com/team/buddyya/student/repository/ProfileImageRepository.java
  src/main/java/com/team/buddyya/student/service/FindStudentService.java
  src/main/java/com/team/buddyya/student/service/MyPageService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#53 feat: 학생 탈퇴하기, 학생 인증 초기화
  src/main/java/com/team/buddyya/certification/controller/CertificationController.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/student/controller/MyPageController.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 📬 API

#56 feat: 댓글 목록 조회시 comments DTO 제거
  src/main/java/com/team/buddyya/feed/controller/CommentController.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentListResponse.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
Labels: ✨ Feature

#58 feat: 채팅 구현 초기 설정
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomStudentRepository.java
Labels: ✨ Feature, 📬 API

#61 refactor: 논의한 문제에 대해서 리팩토링
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/feed/domain/Bookmark.java
  src/main/java/com/team/buddyya/feed/domain/Comment.java
  src/main/java/com/team/buddyya/feed/domain/CommentInfo.java
  src/main/java/com/team/buddyya/feed/domain/FeedImage.java
  src/main/java/com/team/buddyya/feed/domain/FeedUserAction.java
  src/main/java/com/team/buddyya/feed/domain/Like.java
  src/main/java/com/team/buddyya/feed/respository/BookmarkRepository.java
  src/main/java/com/team/buddyya/feed/respository/FeedRepository.java
  src/main/java/com/team/buddyya/feed/respository/LikeRepository.java
  src/main/java/com/team/buddyya/feed/service/BookmarkService.java
  src/main/java/com/team/buddyya/feed/service/CategoryService.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedImageService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/feed/service/LikeService.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/application-local.properties
Labels: 🔨 Refactor

#63 feat: 웹 소켓을 통한 실시간 채팅 전송 구현
  build.gradle
  src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
  src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/MessageType.java
  src/main/java/com/team/buddyya/chatting/dto/request/ChatMessage.java
  src/main/java/com/team/buddyya/chatting/dto/request/CreateChatroomRequest.java
  src/main/java/com/team/buddyya/chatting/dto/response/CreateChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomStudentRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatHandler.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/common/config/WebSocketConfig.java
Labels: ✨ Feature, 📬 API

#70 feat: 채팅방 목록, 채팅 조회, 채팅방 나가기 기능
  build.gradle
  src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/chatting/dto/request/ChatMessage.java
  src/main/java/com/team/buddyya/chatting/dto/request/CreateChatroomRequest.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatMessageListResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatMessageResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/CreateChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/LeaveChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/exception/ChatException.java
  src/main/java/com/team/buddyya/chatting/exception/ChatExceptionType.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomStudentRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/common/config/SwaggerConfig.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/resources/application-local.properties
Labels: ✨ Feature, 📬 API

#75 fix: spring security 경로 수정과 jwt 토큰 파싱 수정 (#74)
  src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
Labels: 🐞 BugFix

#80 feat: 채팅방 사진 전송, 채팅방 사용되지 않는 세션 종료, 수정 사항 변경
  src/main/java/com/team/buddyya/BuddyyaApplication.java
  src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
  src/main/java/com/team/buddyya/chatting/domain/Chat.java
  src/main/java/com/team/buddyya/chatting/domain/Chatroom.java
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/chatting/domain/MessageType.java
  src/main/java/com/team/buddyya/chatting/dto/request/ChatImageRequest.java
  src/main/java/com/team/buddyya/chatting/dto/request/ChatMessage.java
  src/main/java/com/team/buddyya/chatting/dto/request/CreateChatroomRequest.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatMessageResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/CreateChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatHandler.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/domain/S3DirectoryName.java
  src/main/java/com/team/buddyya/common/service/S3UploadService.java
Labels: ✨ Feature, 📬 API
