Repository buddy-ya/be, pull requests merged in 2025-04, with the labels that each got.

#242 fix: 핸드폰 인증번호 검증 시 udId를 nullable하게 받도록 수정
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
Labels: 🐞 BugFix, 🔨 Refactor

#235 feat: 피드 대학별 조회 반영
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedListRequest.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedUpdateRequest.java
  src/main/java/com/team/buddyya/feed/dto/response/comment/CommentResponse.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/repository/FeedRepository.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: 🔨 Refactor

#243 feat: 피드 탭 정보 DTO에 제공
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
Labels: ✨ Feature, 📬 API

#239 feat: 친구 초대 이벤트 기능 구현
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/repository/RegisteredPhoneRepository.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/dto/request/ValidateInvitationCodeRequest.java
  src/main/java/com/team/buddyya/student/dto/response/InvitationCodeResponse.java
  src/main/java/com/team/buddyya/student/dto/response/ValidateInvitationCodeResponse.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/service/InvitationService.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/resources/db/migration/V15__Add_registered_phone_invitation_code.sql
Labels: ✨ Feature

#228 feat: 마이페이지 조회 시 UserResponse에 totalUnreadCount 필드 추가
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: ✨ Feature

#247 fix: 추천인 코드에 자신의 추천인 코드를 입력 할 시 혜택받지 못하도록 수정
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/service/InvitationService.java
Labels: 🐞 BugFix

#250 feat: 기획안 기반으로 PointType별 포인트 변경값 설정
  src/main/java/com/team/buddyya/point/domain/PointType.java
Labels: ✨ Feature

#251 refactor: 학생증 다시 제출 시 반려 사유 제거, 앱 진입 시 정지 상태 업데이트
  src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
Labels: 🔨 Refactor

#256 feat: 매칭 시 프로필 미완성 시 예외 처리
  src/main/java/com/team/buddyya/match/dto/response/MatchResponse.java
  src/main/java/com/team/buddyya/match/dto/response/MatchStatusResponse.java
  src/main/java/com/team/buddyya/match/exception/MatchExceptionType.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/java/com/team/buddyya/student/domain/MatchingProfile.java
Labels: ✨ Feature

#257 feat: 응답 없는 매칭 사용자를 관리자에게 신고하고 포인트 환급 기능
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/report/domain/ReportType.java
  src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java
Labels: ✨ Feature

#263 fix: 테스트 계정으로 로그인 성공 시 send_message_count 초기화
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
Labels: 🐞 BugFix

#266 refactor: report type varchar로 수정
  src/main/resources/db/migration/V17_update_report_type.sql
Labels: 🔨 Refactor

#265 feat: 매칭 성공 후 다음날 자정부터 다시 요청 가능하도록 제한
  src/main/java/com/team/buddyya/match/domain/MatchedHistory.java
  src/main/java/com/team/buddyya/match/exception/MatchExceptionType.java
  src/main/java/com/team/buddyya/match/repository/MatchedHistoryRepository.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/resources/db/migration/V18__Add_matched_history_created_date.sql
Labels: ✨ Feature

#258 refactor: 외국인 유저들이 외국인 유저들과도 매칭이 될 수 있게 수정
  src/main/java/com/team/buddyya/match/domain/MatchRequest.java
  src/main/java/com/team/buddyya/match/domain/NationalityType.java
  src/main/java/com/team/buddyya/match/dto/request/MatchCreateRequest.java
  src/main/java/com/team/buddyya/match/repository/MatchRequestRepository.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/resources/db/migration/V19__Add_match_request_nationality_type.sql
Labels: 🔨 Refactor

#261 feat: 추천인 코드 이벤트 참여 시 추천인에게 포인트 지급 알림 기능 추가
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/student/service/InvitationService.java
Labels: ✨ Feature

#270 feat: 매칭 요청을 거절하거나 24시간이 지났을 경우 포인트 환급 로직 추가
  src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
Labels: ✨ Feature

#275 refactor: 채팅 요청 관련 포인트 로직 제거
  src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
  src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
Labels: 🔨 Refactor

#276 refactor: 문자 인증 코드 전송은 영문으로 수정
  src/main/java/com/team/buddyya/certification/service/MessageSendService.java
Labels: 🔨 Refactor

#282 refactor: 신고 시 게시글 이미지 삭제 x, 로그 정리
  src/main/java/com/team/buddyya/auth/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/team/buddyya/auth/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/team/buddyya/auth/jwt/JwtAuthFilter.java
  src/main/java/com/team/buddyya/auth/jwt/JwtUtils.java
  src/main/java/com/team/buddyya/auth/jwt/WebSocketAuthInterceptor.java
  src/main/java/com/team/buddyya/auth/service/AuthService.java
  src/main/java/com/team/buddyya/chatting/service/ChatHandler.java
  src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/common/config/LoggingFilter.java
  src/main/java/com/team/buddyya/common/config/WebSocketConfig.java
  src/main/java/com/team/buddyya/common/exception/GlobalExceptionHandler.java
  src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/report/repository/ReportRepository.java
  src/main/java/com/team/buddyya/student/domain/CharacterProfileImage.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
Labels: 🌏 Deploy, 🔨 Refactor

#286 refactor: match 로그 추가, 계정 생성 시 id 로그 추가
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
Labels: ⚙ Setting

#304 feat: 출석 이벤트 포인트 지급 기능 구현
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V22__Add_last_attendance_date_registred_phone_info.sql
Labels: ✨ Feature

#308 refactor: 매칭 알림 본문 개선 및 포인트 변화 시 현재 포인트 포함
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/java/com/team/buddyya/notification/domain/RequestNotification.java
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
  src/main/java/com/team/buddyya/student/service/InvitationService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#310 refactor: getUserInfo메서드에서 출석 이벤트 참여 포인트 지급 기능 주석 처리
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#306 Refactor: 채팅 요청 생성 로직 변경 및 피드 생성시 프로필 공개 여부 포함
  src/main/java/com/team/buddyya/chatting/controller/ChatRequestController.java
  src/main/java/com/team/buddyya/chatting/exception/ChatExceptionType.java
  src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatRequestService.java
  src/main/java/com/team/buddyya/feed/domain/Bookmark.java
  src/main/java/com/team/buddyya/feed/domain/Feed.java
  src/main/java/com/team/buddyya/feed/domain/FeedLike.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedCreateRequest.java
  src/main/java/com/team/buddyya/feed/dto/request/feed/FeedUpdateRequest.java
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/service/BookmarkService.java
  src/main/java/com/team/buddyya/feed/service/FeedLikeService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/resources/db/migration/V23__Add_is_profile_visible_to_feed.sql
  src/main/resources/db/migration/V24__Update_bookmark_unique_feed_student.sql
  src/main/resources/db/migration/V25__Update_feedLike_unique_feed_student.sql
Labels: 🔨 Refactor
