Repository buddy-ya/be, pull requests merged in 2025-03, with the labels that each got.

#149 refactor: 채팅방 response에 buddyId 추가
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomDetailResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomListResponse.java
  src/main/java/com/team/buddyya/chatting/dto/response/ChatroomResponse.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRequestRepository.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
Labels: 📬 API

#154 feat: 채팅방 생성 시 생성 메시지 하나 증가 & 읽지 않은 메시지 반환 로직 수정
  src/main/java/com/team/buddyya/chatting/domain/ChatroomStudent.java
  src/main/java/com/team/buddyya/chatting/service/ChatService.java
Labels: 📬 API

#161 feat: 대학교 조회 기능 구현
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/University.java
  src/main/java/com/team/buddyya/student/dto/response/UniversityResponse.java
  src/main/java/com/team/buddyya/student/repository/UniversityRepository.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/java/com/team/buddyya/student/service/UniversityService.java
  src/main/resources/db/migration/V5__Add_university_active_column.sql
Labels: ✨ Feature, 📬 API

#165 fix: 피드 조회, 댓글 차단 조회 로직 변경
  src/main/java/com/team/buddyya/feed/dto/response/feed/FeedResponse.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
Labels: 🐞 BugFix, 📬 API

#167 fix: 자기가 쓴 글에 댓글 달 때 스스로에게 알림 오는 오류 수정
  src/main/java/com/team/buddyya/feed/domain/Feed.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
Labels: 🐞 BugFix

#170 fix: 자기 피드 대댓글 알림 오류 수정
  src/main/java/com/team/buddyya/feed/service/CommentService.java
Labels: 🐞 BugFix

#146 feat: 관리자 제재 기능 및 학생증 반려 사유 추가
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/dto/request/BanRequest.java
  src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
  src/main/java/com/team/buddyya/admin/dto/response/AdminChatMessageResponse.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/certification/domain/StudentIdCard.java
  src/main/java/com/team/buddyya/certification/dto/response/StudentIdCardResponse.java
  src/main/java/com/team/buddyya/certification/service/CertificationService.java
  src/main/java/com/team/buddyya/chatting/repository/ChatRepository.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
  src/main/java/com/team/buddyya/feed/service/FeedService.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/dto/response/UserBanStatusResponse.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V5__Add_student_banned_field.sql
Labels: ✨ Feature, 📬 API

#172 fix: flyway 버전 수정
  src/main/resources/db/migration/V6__Add_student_banned_field.sql
Labels: ✨ Feature

#176 fix: 대댓글의 주인이 자신의 댓글에 대댓글을 달 때 알림 오류 수정
  src/main/java/com/team/buddyya/feed/domain/Comment.java
  src/main/java/com/team/buddyya/feed/service/CommentService.java
Labels: 🐞 BugFix

#178 refactor: 대학교 이메일 인증 외국인일 경우에 영문 이메일 전송
  src/main/java/com/team/buddyya/certification/service/EmailSendService.java
  src/main/resources/templates/email_english.html
  src/main/resources/templates/email_korean.html
Labels: 🔨 Refactor

#184 refactor: 사진 전송 문제 해결하여 security 원상 복구
  src/main/java/com/team/buddyya/chatting/controller/ChatController.java
Labels: 🔨 Refactor

#156 fix: 채팅 요청 수락 알림 전송 개행 오류 수정
  src/main/java/com/team/buddyya/notification/service/NotificationService.java
Labels: 🐞 BugFix

#182 feat: 테스트 계정 목록 DB 생성
  src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
  src/main/java/com/team/buddyya/certification/domain/TestAccount.java
  src/main/java/com/team/buddyya/certification/dto/request/TestAccountRequest.java
  src/main/java/com/team/buddyya/certification/dto/response/TestAccountResponse.java
  src/main/java/com/team/buddyya/certification/repository/TestAccountRepository.java
  src/main/java/com/team/buddyya/certification/service/MessageSendService.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/resources/db/migration/V7__create_test_account_table.sql
Labels: ✨ Feature, 📬 API

#199 fix: Long은 wrapper 클래스이므로 equals로 비교하고 불필요한 로그 삭제
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🐞 BugFix

#200 refactor: 탈퇴 시 핸드폰번호와 이메일을 임의값 겹칠 것을 대비하여 UUID 범위를 증가
  src/main/java/com/team/buddyya/student/domain/Student.java
Labels: 🔨 Refactor

#202 refactor: ExpoToken의 토큰 nullable 허용
  src/main/java/com/team/buddyya/notification/domain/ExpoToken.java
Labels: 🔨 Refactor

#188 refactor: SecurityConfig에서 이미지 전송 오류 수정을 위해 변경했던 node관련 설정 제거
  src/main/java/com/team/buddyya/common/config/SecurityConfig.java
Labels: 🔨 Refactor

#158 feat: 로그 아웃 기능 구현
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Avatar.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: ✨ Feature, 📬 API

#203 feat: 프론트와 논의된 api 수정
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/dto/request/StudentVerificationRequest.java
  src/main/java/com/team/buddyya/admin/dto/response/StudentIdCardResponse.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/report/exception/ReportException.java
  src/main/java/com/team/buddyya/report/exception/ReportExceptionType.java
  src/main/java/com/team/buddyya/report/repository/ReportRepository.java
Labels: 📬 API, 🔨 Refactor

#204 refactor: 활동 대학교 조회 응답 DTO에 대학교 아이디 추가
  src/main/java/com/team/buddyya/student/dto/response/UniversityResponse.java
Labels: 🔨 Refactor

#143 feat: 포인트 기능
  src/main/java/com/team/buddyya/student/domain/Block.java
  src/main/java/com/team/buddyya/student/domain/Point.java
  src/main/java/com/team/buddyya/student/domain/PointStatus.java
  src/main/java/com/team/buddyya/student/domain/PointType.java
  src/main/java/com/team/buddyya/student/exception/StudentExceptionType.java
  src/main/java/com/team/buddyya/student/repository/PointRepository.java
  src/main/java/com/team/buddyya/student/repository/PointStatusRepository.java
  src/main/java/com/team/buddyya/student/service/OnBoardingService.java
  src/main/java/com/team/buddyya/student/service/PointService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V9__Create_point_table.sql
Labels: ✨ Feature

#210 refactor: 매칭 요청시 ALL or MALE or FEMALE로 성별을 받는 것으로 수정
  src/main/java/com/team/buddyya/match/domain/GenderType.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
Labels: 🔨 Refactor

#206 refactor: 프론트와 논의된 api 2차 수정
  src/main/java/com/team/buddyya/admin/controller/AdminController.java
  src/main/java/com/team/buddyya/admin/dto/request/BanRequest.java
  src/main/java/com/team/buddyya/admin/service/AdminService.java
  src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
  src/main/java/com/team/buddyya/certification/domain/AdminAccount.java
  src/main/java/com/team/buddyya/certification/dto/request/AdminAccountRequest.java
  src/main/java/com/team/buddyya/certification/dto/response/AdminAccountResponse.java
  src/main/java/com/team/buddyya/certification/repository/AdminAccountRepository.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/report/exception/ReportExceptionType.java
  src/main/java/com/team/buddyya/report/repository/ReportRepository.java
  src/main/java/com/team/buddyya/report/service/ReportService.java
  src/main/java/com/team/buddyya/student/controller/UserController.java
  src/main/java/com/team/buddyya/student/domain/Student.java
  src/main/java/com/team/buddyya/student/dto/response/UserBanStatusResponse.java
  src/main/java/com/team/buddyya/student/dto/response/UserResponse.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V8__create_admin_account_and_add_ban_reason_to_student.sql
Labels: 📬 API

#212 매칭 성공 시 응답값 추가 및 chatRoodId 오타 수정
  src/main/java/com/team/buddyya/match/dto/response/MatchResponse.java
  src/main/java/com/team/buddyya/match/dto/response/MatchStatusResponse.java
Labels: 🐞 BugFix, 🔨 Refactor

#214 feat: 유저의 포인트 기록 조회 기능 구현
  src/main/java/com/team/buddyya/point/controller/PointController.java
  src/main/java/com/team/buddyya/point/domain/PointChangeType.java
  src/main/java/com/team/buddyya/point/domain/PointType.java
  src/main/java/com/team/buddyya/point/dto/PointListResponse.java
  src/main/java/com/team/buddyya/point/dto/PointResponse.java
  src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
  src/main/java/com/team/buddyya/point/service/PointService.java
Labels: ✨ Feature

#218 refactor: 포인트 기록을 최신순으로 반환
  src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
  src/main/java/com/team/buddyya/point/service/PointService.java
Labels: 🔨 Refactor

#225 refactor: 회원 탈퇴 시 매칭 요청을 삭제하고 탈퇴하거나 차단한 유저와 매칭되지 않도록 수정
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
Labels: 🔨 Refactor

#222 refactor: 매칭을 통해 생성된 채팅방 아이디를 MatchRequest에 저장
  src/main/java/com/team/buddyya/chatting/repository/ChatroomRepository.java
  src/main/java/com/team/buddyya/match/domain/MatchRequest.java
  src/main/java/com/team/buddyya/match/service/BasicMatchService.java
  src/main/resources/db/migration/V12__Add_chatroom_Id_to_matchRequest.sql
Labels: 🔨 Refactor

#223 refactor: 회원 탈퇴 후 즉시 재가입 시 혜택이 중복 지급되지 않도록 방지
  src/main/java/com/team/buddyya/certification/controller/PhoneAuthenticationController.java
  src/main/java/com/team/buddyya/certification/domain/RegisteredPhone.java
  src/main/java/com/team/buddyya/certification/service/PhoneAuthenticationService.java
  src/main/java/com/team/buddyya/point/repository/PointStatusRepository.java
  src/main/java/com/team/buddyya/point/service/PointService.java
  src/main/java/com/team/buddyya/student/service/StudentService.java
  src/main/resources/db/migration/V13__Add_has_withdrawn_to_registered_phone.sql
Labels: 🔨 Refactor

#237 fix: 1004 에러 코드가 중복되었으므로 SMS 인증 초과 예외를 1005번 에러코드로 수정
  src/main/java/com/team/buddyya/certification/exception/PhoneAuthenticationExceptionType.java
Labels: 🐞 BugFix
